### ISSUE TITLE
date error

### ISSUE THREAD

**Issue by jlslinux** [wfx/Enso#1]
PROCESSING...
nothing todo for: efl
nothing todo for: python-efl
nothing todo for: enlightenment
nothing todo for: econnman
nothing todo for: terminology
nothing todo for: rage
nothing todo for: enventor
nothing todo for: eflete
nothing todo for: edi
nothing todo for: eluminance
nothing todo for: epymc
nothing todo for: enter
nothing todo for: egitu
nothing todo for: epack
jls@pc1:~/Enso$ ./enso.sh
PREPARE ENSO
LOAD DISTRIBUTION CONFIGURATION
LOAD PACKAGE CONFIGURATION
LOG TIMESTAP
date: data "%Y/%m/%d_%T" non valida
PROCESSING ALL PACKAGE ACTIONS?
Press [Enter] to continue or [CTRL+C] to cancel...

**Comment by wfx** [comment]
Ahhh! ok sorry :)
fixed.

Note: dont answer with some glass of wine!
